import type {
  ActivityEvent,
  AnalyticsOverview,
  ApiKey,
  Audience,
  BillingInfo,
  Campaign,
  ChangelogEntry,
  FeedbackComment,
  FeedbackCluster,
  FeedbackRequest,
  Integration,
  PublicReleaseComment,
  Release,
  RoadmapItem,
  TeamMember,
  Webhook,
  WebhookDelivery,
  WorkspaceBranding,
  WorkspaceSettings,
} from "@/types";

export const mockWorkspace = {
  id: "ws_acme",
  name: "Acme",
  slug: "acme",
  plan: "pro" as const,
};

export const mockReleases: Release[] = [
  {
    id: "rel_1",
    title: "Dark Mode",
    summary: "A more comfortable way to use Acme at night and in low-light environments.",
    body: "<p>You can now switch between light and dark themes, follow your system preference, or set a default for your workspace.</p><ul><li>Switch themes from settings</li><li>Follow system theme automatically</li><li>Per-user preference saved</li></ul>",
    status: "published",
    channels: ["changelog", "email", "in_app"],
    category: "Feature",
    tags: ["ui", "accessibility"],
    audienceId: "aud_all",
    publishedAt: "2026-09-07T10:00:00Z",
    sourceRefs: [{ id: "src_1", type: "github", label: "acme/app#482", url: "https://github.com" }],
    views: 842,
    reactions: 184,
    comments: 3,
    createdAt: "2026-09-05T08:00:00Z",
    updatedAt: "2026-09-07T10:00:00Z",
    slug: "dark-mode",
    featured: true,
    cta: { label: "Try Dark Mode", url: "/settings/appearance" },
    channelVariants: {
      email: {
        channel: "email",
        title: "Dark mode is ready for your workspace",
        summary: "A calmer, lower-light way to work in Acme is ready whenever you are.",
        body: "<p>Hi there,</p><p>Dark mode is now available across your Acme workspace. Switch whenever you need a more comfortable view, or let Acme follow your system preference.</p><p>Thanks,<br />The Acme team</p>",
        subject: "Dark mode is ready for your workspace",
        previewText: "A calmer way to work in Acme, ready whenever you are.",
      },
      in_app: {
        channel: "in_app",
        format: "feed",
        title: "Dark mode, ready when you are",
        summary: "A calmer way to use Acme in lower-light environments.",
        body: "<p>Choose dark mode in appearance settings, or let Acme follow your system preference.</p>",
      },
    },
    media: [
      {
        id: "media_dark_mode_workspace",
        type: "image",
        url: "/mock-dark-mode-workspace.svg",
        alt: "Acme workspace dashboard shown in dark mode with release metrics and recent updates",
        caption: "A calmer workspace that stays comfortable after hours.",
      },
      {
        id: "media_dark_mode_walkthrough",
        type: "video",
        url: "mock://dark-mode-walkthrough",
        posterUrl: "/mock-dark-mode-walkthrough.svg",
        alt: "Preview of a walkthrough for switching Acme to dark mode",
        caption: "A 24-second walkthrough of the new appearance controls.",
      },
    ],
    createdBy: "Don Jesus",
    reviewedBy: "Alex Chen",
    publishedBy: "Alex Chen",
  },
  {
    id: "rel_2",
    title: "Advanced Reporting",
    summary: "Your reports just got a lot more powerful with custom filters and exports.",
    body: "<p>Build richer reports with multi-dimensional filters, saved views, and one-click CSV export.</p>",
    status: "published",
    channels: ["changelog", "in_app"],
    category: "Feature",
    tags: ["analytics", "reports"],
    publishedAt: "2026-08-28T14:00:00Z",
    sourceRefs: [{ id: "src_2", type: "linear", label: "ACM-142", url: "https://linear.app" }],
    views: 621,
    reactions: 96,
    comments: 2,
    createdAt: "2026-08-20T09:00:00Z",
    updatedAt: "2026-08-28T14:00:00Z",
    slug: "advanced-reporting",
    featured: false,
    cta: { label: "Explore reporting", url: "/app/analytics" },
    channelVariants: {
      in_app: {
        channel: "in_app",
        format: "banner",
        title: "Build sharper reports with less setup",
        summary: "Advanced Reporting gives your team saved views, deeper filters, and exports when you need them.",
        body: "<p>Use the new reporting controls to focus on the metrics that matter, then save or export the view for your team.</p>",
      },
    },
  },
  {
    id: "rel_3",
    title: "Team Permissions",
    summary: "Granular roles so the right people can review and publish updates.",
    body: "<p>Assign Owner, Admin, Product Manager, Marketer, Developer, or Viewer roles with approval workflows.</p>",
    status: "scheduled",
    channels: ["changelog", "email"],
    category: "Improvement",
    tags: ["team", "security"],
    audienceId: "aud_pro",
    scheduledAt: "2026-09-09T09:00:00Z",
    sourceRefs: [{ id: "src_3", type: "manual", label: "Product brief" }],
    views: 0,
    reactions: 0,
    comments: 0,
    createdAt: "2026-09-01T11:00:00Z",
    updatedAt: "2026-09-06T16:00:00Z",
    slug: "team-permissions",
    featured: false,
    createdBy: "Don Jesus",
    reviewedBy: "Alex Chen",
  },
  {
    id: "rel_4",
    title: "CSV Export",
    summary: "Export any table to CSV in one click.",
    body: "<p>Download filtered data from reports, feedback, and analytics views.</p>",
    status: "published",
    channels: ["changelog"],
    category: "Improvement",
    tags: ["export"],
    publishedAt: "2026-08-15T12:00:00Z",
    sourceRefs: [],
    views: 412,
    reactions: 52,
    comments: 0,
    createdAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-08-15T12:00:00Z",
    slug: "csv-export",
    featured: false,
  },
  {
    id: "rel_5",
    title: "Performance Improvements",
    summary: "Faster page loads and smoother interactions across the dashboard.",
    body: "<p>We reduced initial load time by 40% and optimized list rendering for large datasets.</p>",
    status: "draft",
    channels: ["changelog"],
    category: "Improvement",
    tags: ["performance"],
    sourceRefs: [{ id: "src_4", type: "github", label: "acme/app#501" }],
    views: 0,
    reactions: 0,
    comments: 0,
    createdAt: "2026-09-07T15:00:00Z",
    updatedAt: "2026-09-07T15:00:00Z",
    slug: "performance-improvements",
    featured: false,
  },
  {
    id: "rel_6",
    title: "Saved Filters",
    summary: "Save and reuse filter combinations across feedback and analytics.",
    body: "<p>Build custom views once and return to them anytime. Share filters with your team.</p>",
    status: "in_review",
    channels: ["changelog", "in_app"],
    category: "Feature",
    tags: ["filters", "productivity"],
    sourceRefs: [{ id: "src_5", type: "linear", label: "ACM-198" }],
    views: 0,
    reactions: 0,
    comments: 0,
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-07T09:00:00Z",
    slug: "saved-filters",
    featured: false,
  },
];

export const mockPublicReleaseComments: PublicReleaseComment[] = [
  {
    id: "public_comment_1",
    releaseId: "rel_1",
    author: "Mina Shah",
    body: "The system setting is especially helpful for our team members who switch between home and office.",
    createdAt: "2026-09-07T11:18:00Z",
  },
  {
    id: "public_comment_2",
    releaseId: "rel_1",
    author: "Jordan Patel",
    body: "Thank you for making the contrast feel so considered. Dark mode looks great.",
    createdAt: "2026-09-07T13:42:00Z",
  },
  {
    id: "public_comment_3",
    releaseId: "rel_1",
    author: "Avery Kim",
    body: "The new appearance controls were easy to find and set up.",
    createdAt: "2026-09-08T08:05:00Z",
  },
  {
    id: "public_comment_4",
    releaseId: "rel_2",
    author: "Morgan Lee",
    body: "Saved views will save us a lot of time each week.",
    createdAt: "2026-08-28T16:10:00Z",
  },
  {
    id: "public_comment_5",
    releaseId: "rel_2",
    author: "Taylor Brooks",
    body: "The CSV export is a welcome addition to our reporting workflow.",
    createdAt: "2026-08-29T09:24:00Z",
  },
];

export const mockFeedback: FeedbackRequest[] = [
  {
    id: "fb_1",
    title: "Saved Filters",
    description: "Let me save a filter for later and reuse it across views.",
    votes: 128,
    comments: 24,
    status: "planned",
    tags: ["filters", "productivity"],
    aiClusterId: "cluster_1",
    roadmapItemId: "rm_3",
    source: "customer",
    createdAt: "2026-08-01T10:00:00Z",
    priority: "high",
    internalNotes: "Strong signal from Pro teams building repeatable reporting workflows.",
  },
  {
    id: "fb_2",
    title: "Scheduled Reports",
    description: "Can reports be emailed automatically on a schedule?",
    votes: 74,
    comments: 12,
    status: "reviewing",
    tags: ["reports", "email"],
    aiClusterId: "cluster_2",
    roadmapItemId: "rm_4",
    source: "customer",
    createdAt: "2026-07-15T08:00:00Z",
    priority: "medium",
    internalNotes: "Validate whether weekly scheduling is enough before scoping recurring delivery.",
  },
  {
    id: "fb_3",
    title: "Dark mode please",
    description: "Please add dark mode for night usage.",
    votes: 247,
    comments: 38,
    status: "shipped",
    tags: ["ui", "accessibility"],
    aiClusterId: "cluster_3",
    roadmapItemId: "rm_1",
    linkedReleaseId: "rel_1",
    source: "customer",
    createdAt: "2026-06-01T12:00:00Z",
    priority: "high",
  },
  {
    id: "fb_4",
    title: "Night theme support",
    description: "I need a night theme for late work sessions.",
    votes: 89,
    comments: 11,
    status: "shipped",
    tags: ["ui"],
    aiClusterId: "cluster_3",
    roadmapItemId: "rm_1",
    source: "customer",
    createdAt: "2026-06-05T14:00:00Z",
    priority: "medium",
  },
  {
    id: "fb_5",
    title: "Bulk CSV export",
    description: "Export multiple report tables at once.",
    votes: 82,
    comments: 9,
    status: "shipped",
    tags: ["export"],
    roadmapItemId: "rm_5",
    linkedReleaseId: "rel_4",
    source: "customer",
    createdAt: "2026-07-20T09:00:00Z",
    priority: "low",
  },
];

export const mockFeedbackComments: FeedbackComment[] = [
  {
    id: "comment_1",
    feedbackId: "fb_1",
    author: "Avery Kim",
    body: "Saved filters would make our weekly reporting process much faster.",
    createdAt: "2026-08-03T09:40:00Z",
  },
  {
    id: "comment_2",
    feedbackId: "fb_1",
    author: "Alex Chen",
    body: "We are exploring how this can work across feedback and analytics views.",
    createdAt: "2026-08-08T15:20:00Z",
    isInternal: true,
  },
  {
    id: "comment_3",
    feedbackId: "fb_2",
    author: "Morgan Lee",
    body: "A Monday morning email with our key numbers would be ideal.",
    createdAt: "2026-07-18T12:10:00Z",
  },
  {
    id: "comment_4",
    feedbackId: "fb_3",
    author: "Jordan Patel",
    body: "The system theme option is exactly what our team needed.",
    createdAt: "2026-09-07T11:30:00Z",
  },
];

export const mockClusters: FeedbackCluster[] = [
  {
    id: "cluster_3",
    title: "Dark Mode",
    votes: 247,
    comments: 38,
    demand: "high",
    topNeed: "Comfortable usage at night",
    representativeQuotes: [
      "Please add dark mode.",
      "I need a night theme.",
      "Can you support dark UI?",
    ],
    feedbackIds: ["fb_3", "fb_4"],
  },
  {
    id: "cluster_1",
    title: "Saved Filters",
    votes: 128,
    comments: 24,
    demand: "medium",
    topNeed: "Reuse filter combinations across views",
    representativeQuotes: ["Let me save a filter for later."],
    feedbackIds: ["fb_1"],
  },
  {
    id: "cluster_2",
    title: "Scheduled Reports",
    votes: 74,
    comments: 12,
    demand: "medium",
    topNeed: "Automated report delivery",
    representativeQuotes: ["Can reports be emailed automatically?"],
    feedbackIds: ["fb_2"],
  },
];

export const mockRoadmap: RoadmapItem[] = [
  {
    id: "rm_1",
    title: "Dark Mode",
    description: "Theme switching with system preference support.",
    status: "shipped",
    votes: 247,
    linkedFeedbackIds: ["fb_3", "fb_4"],
    linkedReleaseId: "rel_1",
    targetDate: "2026-09-07",
  },
  {
    id: "rm_2",
    title: "Advanced Reporting",
    description: "Custom filters, saved views, and exports.",
    status: "now",
    votes: 128,
    linkedFeedbackIds: [],
    linkedReleaseId: "rel_2",
    targetDate: "2026-09-15",
  },
  {
    id: "rm_3",
    title: "Saved Filters",
    description: "Save and share filter combinations.",
    status: "next",
    votes: 128,
    linkedFeedbackIds: ["fb_1"],
    targetDate: "2026-10-01",
  },
  {
    id: "rm_4",
    title: "Scheduled Reports",
    description: "Email reports on a recurring schedule.",
    status: "later",
    votes: 74,
    linkedFeedbackIds: ["fb_2"],
  },
  {
    id: "rm_5",
    title: "CSV Export",
    description: "One-click CSV export from any table.",
    status: "shipped",
    votes: 82,
    linkedFeedbackIds: ["fb_5"],
    linkedReleaseId: "rel_4",
  },
];

export const mockAnalytics: AnalyticsOverview = {
  views: 2481,
  clicks: 391,
  ctaClicks: 148,
  reactions: 184,
  engagement: 38,
  channelBreakdown: [
    { channel: "changelog", percentage: 52 },
    { channel: "widget", percentage: 31 },
    { channel: "email", percentage: 17 },
  ],
  topReleases: [
    { id: "rel_1", title: "Dark Mode", views: 842, engagement: 42 },
    { id: "rel_2", title: "Advanced Reporting", views: 621, engagement: 35 },
    { id: "rel_4", title: "CSV Export", views: 412, engagement: 28 },
  ],
  releasePerformance: [
    { id: "rel_2", title: "Advanced Reporting", score: 92 },
    { id: "rel_1", title: "Dark Mode", score: 88 },
    { id: "rel_3", title: "Team Permissions", score: 65 },
  ],
  audiencePerformance: [
    { audience: "Pro customers", engagement: 46, recipients: 1248 },
    { audience: "Beta users", engagement: 41, recipients: 312 },
    { audience: "All users", engagement: 32, recipients: 3240 },
  ],
};

export const mockIntegrations: Integration[] = [
  {
    id: "int_1",
    provider: "github",
    name: "GitHub",
    status: "connected",
    detail: "Acme / main",
    lastSync: "2026-09-08T06:37:00Z",
  },
  {
    id: "int_2",
    provider: "linear",
    name: "Linear",
    status: "connected",
    detail: "Acme Workspace",
    lastSync: "2026-09-08T06:30:00Z",
  },
  {
    id: "int_3",
    provider: "gitlab",
    name: "GitLab",
    status: "available",
    detail: "",
    lastSync: null,
  },
  {
    id: "int_4",
    provider: "jira",
    name: "Jira",
    status: "available",
    detail: "",
    lastSync: null,
  },
];

export const mockTeam: TeamMember[] = [
  { id: "tm_1", name: "Don Jesus", email: "don@acme.com", role: "owner", status: "active" },
  { id: "tm_2", name: "Alex Chen", email: "alex@acme.com", role: "product_manager", status: "active" },
  { id: "tm_3", name: "Maya Patel", email: "maya@acme.com", role: "marketer", status: "invited" },
  { id: "tm_4", name: "Sam Rivera", email: "sam@acme.com", role: "developer", status: "active" },
];

export const mockAudiences: Audience[] = [
  { id: "aud_all", name: "All users", size: 3240, rules: { plans: ["free", "pro", "enterprise"] } },
  { id: "aud_pro", name: "Pro customers", size: 1248, rules: { plans: ["pro"] } },
  { id: "aud_beta", name: "Beta users", size: 312, rules: { tags: ["beta"] } },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp_1",
    releaseId: "rel_1",
    subject: "Dark Mode is here",
    previewText: "A more comfortable way to use Acme.",
    from: "Acme Product Team",
    audienceId: "aud_all",
    status: "sent",
    scheduledAt: null,
    sentAt: "2026-09-07T10:30:00Z",
  },
  {
    id: "camp_2",
    releaseId: "rel_3",
    subject: "Team Permissions launching tomorrow",
    previewText: "Granular roles for your team.",
    from: "Acme Product Team",
    audienceId: "aud_pro",
    status: "scheduled",
    scheduledAt: "2026-09-09T08:00:00Z",
    sentAt: null,
  },
];

export const mockChangelogEntries: ChangelogEntry[] = mockReleases
  .filter((r) => r.channels.includes("changelog") && r.status === "published")
  .map((r) => ({
    id: r.id,
    title: r.title,
    summary: r.summary,
    category: r.category,
    tags: r.tags,
    publishedAt: r.publishedAt!,
    slug: r.slug!,
    featured: r.featured ?? false,
    status: r.status,
    reactions: r.reactions,
    comments: r.comments,
  }));

export const mockActivity: ActivityEvent[] = [
  { id: "act_1", type: "ai_generated", message: 'AI generated "Dark Mode"', timestamp: "2026-09-08T07:41:00Z", link: "/app/releases/rel_1", read: false },
  { id: "act_2", type: "approved", message: 'Alex approved "CSV Export"', timestamp: "2026-09-08T07:36:00Z", link: "/app/releases/rel_4", actor: "Alex Chen", read: false },
  { id: "act_3", type: "integration", message: "GitHub detected 4 changes", timestamp: "2026-09-08T07:12:00Z", link: "/app/integrations", read: false },
  { id: "act_4", type: "feedback", message: "32 customers voted for Saved Filters", timestamp: "2026-09-07T14:22:00Z", link: "/app/feedback/fb_1", read: true },
  { id: "act_5", type: "scheduled", message: "Email campaign scheduled", timestamp: "2026-09-07T13:08:00Z", link: "/app/campaigns", read: true },
];

export const mockBilling: BillingInfo = {
  plan: "pro",
  price: 49,
  usagePercent: 82,
  features: ["Releases", "AI generation", "Changelog", "Widget", "Analytics", "Team"],
  invoices: [
    { id: "inv_1", date: "2026-08-01", amount: 49, status: "paid" },
    { id: "inv_2", date: "2026-07-01", amount: 49, status: "paid" },
  ],
  paymentMethod: { brand: "Visa", last4: "4242", expires: "08/29" },
};

export const mockApiKeys: ApiKey[] = [
  { id: "key_1", name: "Production", prefix: "shipbrief_live_", createdAt: "2026-09-07T10:00:00Z", lastUsed: "2026-09-08T06:00:00Z" },
];

export const mockWebhooks: Webhook[] = [
  { id: "wh_1", url: "https://api.example.com/hook", events: ["release.published", "feedback.created"], status: "active", lastDelivery: "2026-09-07T18:00:00Z" },
];

export const mockWebhookDeliveries: WebhookDelivery[] = [
  { id: "delivery_1", webhookId: "wh_1", event: "release.published", status: "success", deliveredAt: "2026-09-07T18:00:00Z", responseCode: 200 },
  { id: "delivery_2", webhookId: "wh_1", event: "feedback.created", status: "success", deliveredAt: "2026-09-06T14:22:00Z", responseCode: 202 },
  { id: "delivery_3", webhookId: "wh_1", event: "release.published", status: "failed", deliveredAt: "2026-09-04T10:15:00Z", responseCode: 502 },
];

export const mockBranding: WorkspaceBranding = {
  logoUrl: null,
  accentColor: "#E40178",
  faviconUrl: null,
  domain: "updates.acme.com",
  domainStatus: "pending",
  publicTheme: "light",
  widgetTheme: "inherit",
};

export const mockSettings: WorkspaceSettings = {
  name: "Acme",
  slug: "acme",
  brandVoice: "Friendly, clear, and customer-focused. Avoid jargon. Lead with benefits.",
  timezone: "America/New_York",
  notifications: {
    emailDigest: true,
    releaseApproved: true,
    feedbackCluster: true,
    integrationErrors: true,
  },
};

export const mockOverview = {
  greeting: "Good morning",
  userName: "Don Jesus",
  metrics: {
    releases: 12,
    drafts: 4,
    views: 2400,
    engagement: 38,
  },
  attention: [
    { id: "att_1", message: "3 AI drafts waiting for review", href: "/app/releases?status=draft", priority: "high" },
    { id: "att_2", message: "2 feedback clusters need a decision", href: "/app/feedback", priority: "medium" },
    { id: "att_3", message: "1 scheduled announcement tomorrow", href: "/app/releases/rel_3", priority: "medium" },
  ],
  customerSignals: [
    { id: "sig_1", title: "Dark Mode", votes: 247, href: "/app/feedback?cluster=cluster_3" },
    { id: "sig_2", title: "CSV Export", votes: 82, href: "/app/feedback/fb_5" },
  ],
};
